"use client";
import { useState } from "react";
import { Inter } from "next/font/google";

import "./globals.css";
// import { counterContext } from "@/store/auth";
import { AuthProvider } from "./store/auth.jsx";
import Navbar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
const inter = Inter({ subsets: ["latin"] });
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  const [user, setUser] = useState("initial Value");
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`${inter.className} `}>
         
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </AuthProvider>
  );
}
