"use client";
import { useState } from "react";
import { Inter } from "next/font/google";

import "./globals.css";
// import { counterContext } from "@/store/auth";
import { AuthProvider } from "./store/auth.jsx";
import Navbar from "@/components/NavBar/NavBar";
import Footer1 from "@/components/footer4/page";
const inter = Inter({ subsets: ["latin"] });
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  const [user, setUser] = useState("initial Value");
  return (
    <AuthProvider>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://unpkg.com/aos@next/dist/aos.css"
          />
        </head>
        <body className={`${inter.className} `}>
          <Navbar />
          {children}
          <Footer1 />
          <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
          <script>AOS.init();</script>
        </body>
      </html>
    </AuthProvider>
  );
}
